[package]
name = "Non-Stationary-MAB"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"      # Provides random number generation
rand_distr = "0.4" # Supports Beta distribution sampling

